version: '3'

services:
          
  jmeter-lg1:
    build: ./loadgenerator
    
    command: ./opt/apache-jmeter-5.1.1/bin/jmeter.sh -s -n -Jclient.rmi.localport=7000 -Jserver.rmi.localport=60000 -Jserver.rmi.ssl.disable=true
    ports:
    - "6000:6000"

        
  jmeter-lg2:
    build: ./loadgenerator
    command: ./opt/apache-jmeter-5.1.1/bin/jmeter.sh -s -n -Jclient.rmi.localport=7000 -Jserver.rmi.localport=60000 -Jserver.rmi.ssl.disable=true
    ports:
    - "6001:6000"
    
  jmeter-controller:
    build: ./controller
    command: ./opt/apache-jmeter-5.1.1/bin/jmeter.sh -n -Jclient.rmi.localport=7000 -Jserver.rmi.localport=60000 -Jserver.rmi.ssl.disable=true
    ports:
    - "7000:7000"
    
    


        


